# Generated by Django 6.0.5 on 2026-05-20 15:30

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pharmacy_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('radiology_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_provider', models.CharField(blank=True, max_length=120)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('insurance', 'Insurance')], db_index=True, max_length=20)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
