# Generated by Django 6.0.5 on 2026-05-20 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_emergency_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, default='system', max_length=80),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'created_at'], name='audit_audit_module_fb6a54_idx'),
        ),
    ]
